"""Anonymous hardware reports and the human-readable card printed by `shura check`.

A report is meant to be pasted into a GitHub issue by the user, so it is built from an allow-list: only the
hardware description, the plan, measured numbers and error texts go in, and error texts are scrubbed of the home
directory, user name and host name. Nothing is ever sent anywhere by this code.
"""
import json

GiB = 1024 ** 3


def scrub(text, *, home=None, user=None, host=None):
    out = str(text)
    for needle, repl in ((home, "~"), (user, "<user>"), (host, "<host>")):
        if needle and len(needle) > 1:
            out = out.replace(needle, repl)
    return out


def _gib(n):
    return f"{n / GiB:.1f} GiB"


def card(hw, plan):
    """Text card for the terminal."""
    cpu, mem = hw["cpu"], hw["memory"]
    bw = mem.get("bandwidth_gbs")
    lines = ["Shura hardware check", "",
             f"  System   : {hw['os']['family']} {hw['os']['arch']} · {cpu['model']} "
             f"({cpu['physical_cores']} cores / {cpu['logical_cores']} threads, {cpu['numa_nodes']} NUMA node"
             f"{'s' if cpu['numa_nodes'] > 1 else ''})",
             f"  Memory   : {_gib(mem['total'])} RAM, " + (f"{bw:.0f} GB/s (measured)" if bw else "speed not measured")]
    for g in hw["gpus"]:
        kind = "unified memory" if g.get("unified") else f"{_gib(g['vram_total'])} VRAM ({_gib(g['vram_used'])} in use)"
        lines.append(f"  GPU      : {g['name']}, {kind}, backends: {', '.join(g.get('backends') or ['?'])}")
    if not hw["gpus"]:
        lines.append("  GPU      : none found (CPU only)")
    for n in hw.get("detection_notes", []):
        lines.append(f"  note     : {n}")
    lines += ["", "Plan"]
    if not plan["ok"]:
        lines += ["  Result   : no model fits this machine", *[f"  Reason   : {r}" for r in plan["reasons"]]]
        return "\n".join(lines)
    s, m, t = plan["settings"], plan["memory"], plan["predicted_tok_s"]
    modes = {"hybrid": "attention and part of the model on the GPU, the rest in RAM", "gpu": "all on the GPU",
             "cpu": "all in RAM, computed by the CPU", "unified": "all in unified memory"}
    lines += [f"  Model    : {plan.get('model_name', plan['model'])}, quant {plan['quant']}",
              f"  Mode     : {plan['mode']} ({modes[plan['mode']]})",
              f"  Context  : {s['context']} tokens, KV cache {s['kv_type']}",
              f"  Backends : {', '.join(plan['backend_candidates'])}" + (" (measured at install)" if plan["needs_probe"] else ""),
              f"  Expected : ~{t['mid']:.0f} tok/s with {plan['speed_by_fill']['typical_tokens']} tokens in the window "
              f"(empty {plan['speed_by_fill']['empty']:.0f}, full {plan['speed_by_fill']['full']:.0f}; "
              f"range {t['low']:.0f}-{t['high']:.0f}), confidence {plan['confidence']}",
              f"  Memory   : RAM {_gib(m['ram_need'])} of {_gib(m['ram_budget'])}"
              + (f" · VRAM {_gib(m['vram_need'])} of {_gib(m['vram_budget'])}" if m["vram_need"] else ""),
              "", "Why"]
    lines += [f"  - {r}" for r in plan["reasons"]]
    if plan["warnings"]:
        lines += ["", "Warnings"] + [f"  - {w}" for w in plan["warnings"]]
    if plan["alternatives"]:
        lines += ["", "Alternatives"] + [f"  - {a['model']} {a['quant']}: ~{a['tok_s']} tok/s" for a in plan["alternatives"]]
    lines += ["", "Predictions are estimates from measured memory speed. The installer measures real speed and corrects them."]
    return "\n".join(lines)


def make_report(hw, plan, *, shura_version="dev", measured=None, errors=None, scrub_args=None):
    """(json_dict, markdown) for a GitHub 'hardware report' issue. Allow-list only."""
    scrub_args = scrub_args or {}
    safe_hw = {"schema": hw["schema"], "os": hw["os"], "cpu": hw["cpu"], "memory": hw["memory"],
               "gpus": [{k: v for k, v in g.items()} for g in hw["gpus"]],
               "detection_notes": [scrub(n, **scrub_args) for n in hw.get("detection_notes", [])]}
    keep = ("ok", "model", "model_name", "quant", "mode", "backend_candidates", "settings", "predicted_tok_s", "speed_by_fill", "confidence",
            "warnings", "reasons")
    data = {"kind": "shura-hardware-report", "shura_version": shura_version, "hardware": safe_hw,
            "plan": {k: plan[k] for k in keep if k in plan}, "measured": measured or {},
            "errors": [scrub(e, **scrub_args) for e in (errors or [])]}
    md = ["## Shura hardware report", "",
          "_Generated by `shura report`. It contains no names, paths or IDs; please read it before posting._", "",
          "```text", card({**hw, "detection_notes": safe_hw["detection_notes"]}, plan), "```", ""]
    if measured:
        md += ["**Measured on this machine:** " + ", ".join(f"{k}: {v}" for k, v in measured.items()), ""]
    if data["errors"]:
        md += ["**Problems seen:**"] + [f"- {e}" for e in data["errors"]] + [""]
    md += ["<details><summary>Machine-readable data</summary>", "", "```json", json.dumps(data, indent=2), "```", "",
           "</details>"]
    return data, "\n".join(md)
